---
abstract: 'Categorize list items into a hash of named sublists.'
author:
  - 'Bill Odom <wnodom@cpan.org>'
generated_by: 'Dist::Zilla::Plugin::MetaYAML version 1.092450'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: List-Categorize
requires:
  Test::Deep: 0
  Test::More: 0
  Test::NoWarnings: 0
version: 0.03
